---
- name: Install and configure Kafdrop
  hosts: zookeeper
  become: yes
  vars:
    zookeeper_host: "{{ inventory_hostname }}"
    kafdrop_version: "3.31.0"
    kafka_broker: "{{ groups['kafka_brokers'][0] }}" 
    
  tasks:
    - name: Install required software
      apt:
        name: ["openjdk-11-jdk", "curl", "unzip"]
        state: present

    - name: Download Kafdrop
      get_url:
        url: "https://github.com/obsidiandynamics/kafdrop/releases/download/{{ kafdrop_version }}/kafdrop-{{ kafdrop_version }}.jar"
        dest: "/tmp/kafdrop-{{ kafdrop_version }}.jar"

    - name: Run Kafdrop
      shell: nohup java -jar /tmp/kafdrop-{{ kafdrop_version }}.jar  --kafka.brokerConnect={{ kafka_broker }}:9092 --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --server.port=9000 & 
      args:
        executable: /bin/bash