---
- name: Set up Kafka
  hosts: kafka_brokers
  become: yes
  vars:
    kafka_version: "2.13-2.6.0"
    kafka_home: "/opt/kafka"
    zookeeper_host: "{{ groups['zookeeper'][0] }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - "openjdk-11-jdk"
        - "curl"
        - "wget"

    - name: Download and extract Kafka
      unarchive:
        src: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ kafka_version }}.tgz"
        dest: "{{ kafka_home }}"
        remote_src: yes
        creates: "{{ kafka_home }}/kafka_{{ kafka_version }}"

    - name: Configure Kafka
      template:
        src: templates/server.properties.j2
        dest: "{{ kafka_home }}/kafka_{{ kafka_version }}/config/server.properties"
      vars:
        #broker_id: "{{ play_hosts.index(inventory_hostname) }}"
        broker_id: "{{ hostvars[inventory_hostname]['kafka_broker_id'] }}"
        
    - name: Start Kafka
      command: "{{ kafka_home }}/kafka_{{ kafka_version }}/bin/kafka-server-start.sh -daemon {{ kafka_home }}/kafka_{{ kafka_version }}/config/server.properties"
