- name: Check Kafka status via ZooKeeper CLI
  hosts: zookeeper
  become: yes
  tasks:
    - name: Check kafka broker list in zookeeper
      command: "/opt/zookeeper/apache-zookeeper-3.6.2-bin/bin/zkCli.sh ls /brokers/ids"
      register: zookeeper_status
      ignore_errors: true

    - name: Print kafka broker list 
      debug:
        var: zookeeper_status.stdout_lines
